add possibility to specify multiple keys at once (-k key1 -k key2 ...)
sebidude/kubecrypt pull request #5
Opened 2019-08-21 13:07 UTC by jonny08152

2019-08-21 14:46 UTC, sebidude commented
I like the idea, but it introduces a confusing behavior when converting from a yaml file with encrypted values to a kubernetes secret. If mutliple keys are specified to find the maps in the yaml file and a key with same name exists in more than one map, the last one will win and the kubernetes secret will not state all the data. 

I suggest to not convert to a kubernetes secret if multiple keys are specified and within the maps behind those keys, keys are same.

Here is how I tested:
```
cat << EOF > values.yaml 
data:
  password: testme
  token: foo
data2:
  password: test2
  token: foo2
safe:
  username: foobary
EOF

./kubecrypt yaml -e -i values.yaml -k data -k data2 -o safe.yaml
./kubecrypt convert foobar --key data -i safe.yaml 
./kubecrypt convert foobar --key data -k data2 -i safe.yaml 

```

It looks fine for a yaml file like this:
```
data:
  password: testme
  token: foo
data2:
  password2: test2
  token2: foo2
safe:
  username: foobary
```

2019-08-21 14:56 UTC, jonny08152 commented
Hmm I see. A solution to this would be to limit the "multiple keys" functionality to **get** and **yaml** even if that introduces some inconsistency in sub-command behaviors. But I think the benefits of having the functionality in those commands outweighs the disadvantages of introduced inconsistencyies.

2019-08-21 17:23 UTC, sebidude commented
What about checking for duplos and stop if a key is already stated in the secrets data?

2019-08-22 07:37 UTC, sebidude commented
Ok. Let's not allow multiple keys for convert.
I'll do a review and you can do the fix then.

2019-08-22 08:18 UTC, sebidude requested changes

2019-08-22 08:18 UTC, sebidude commented on cmd/kubecrypt/main.go
> +	convert.Flag("key", "Keys in the yaml to be used as data for the secret").Required().Short('k').StringsVar(&keynames)
Do not allow multiple keys here as discussed.

2019-08-22 13:00 UTC, jonny08152 commented
multiple keys are now only allowed for **yaml** and **get** sub commands

2019-08-22 13:34 UTC, sebidude requested changes

2019-08-22 13:34 UTC, sebidude commented on cmd/kubecrypt/main.go
> +		keynames = append(keynames, keyname)
Why do we need the keynames here?

2019-08-22 13:37 UTC, jonny08152 commented on cmd/kubecrypt/main.go
> +		keynames = append(keynames, keyname)
We could do it without that line but had to differentiate for one key vs. several keys in **processYamlData()** then.

2019-08-22 14:12 UTC, sebidude commented on cmd/kubecrypt/main.go
> +		keynames = append(keynames, keyname)
got it.

2019-08-22 14:12 UTC, merged